/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Keyring;
import Exceptions.KeyringException;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import GUI.Classes.ActionDialogListener;
import java.awt.Frame;
import java.awt.event.KeyEvent;

/**
 *
 * @author AntoninoBonanno <https://github.com/AntoninoBonanno>
 */
public class NewKeyringDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewKeyring_JDialog
     * @param parent
     * @param modal
     * @param listener <code>ActionDialogListener</code>, listener per l'evento <code>ActionDialog</code>.  
     */
    public NewKeyringDialog(java.awt.Frame parent, boolean modal, ActionDialogListener listener) {
        super(parent, modal);
        initComponents();
        
        this.actionKeyringListener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabelLogo = new javax.swing.JLabel();
        jTextFieldDirectory = new javax.swing.JTextField();
        jButtonSearchDirectory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonConfirm = new javax.swing.JButton();
        jButtonAbort = new javax.swing.JButton();
        jKeyPanel = new GUI.Components.JKeyPanel();
        jButtonCredits = new javax.swing.JButton();

        jFileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        jFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuovo Keyring");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo1.png")));
        setResizable(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jTextFieldDirectory.setText(System.getProperty("user.dir"));
        jTextFieldDirectory.setToolTipText("Cartella di destinazione");
        jTextFieldDirectory.setEnabled(false);
        jTextFieldDirectory.setFocusable(false);

        jButtonSearchDirectory.setText("Cerca");
        jButtonSearchDirectory.setToolTipText("Cerca l'allegato nel computer");
        jButtonSearchDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDirectoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Cartella di destinazione:");

        jTextField_Name.setToolTipText("Nome file");

        jLabel2.setText("Nome file:");

        jButtonConfirm.setText("Conferma");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonAbort.setText("Annulla");
        jButtonAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbortActionPerformed(evt);
            }
        });

        jKeyPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jKeyPanelKeyPressed(evt);
            }
        });

        jButtonCredits.setText("?");
        jButtonCredits.setFocusable(false);
        jButtonCredits.setRequestFocusEnabled(false);
        jButtonCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAbort))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSearchDirectory))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCredits)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCredits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchDirectory))
                .addGap(18, 18, 18)
                .addComponent(jKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirm)
                    .addComponent(jButtonAbort))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDirectoryActionPerformed
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            if(file!=null && file.exists()){
                jTextFieldDirectory.setText(file.getPath());
            }
        } else jTextFieldDirectory.setText(System.getProperty("user.dir"));
    }//GEN-LAST:event_jButtonSearchDirectoryActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        try {            
            Keyring keyring = new Keyring(jKeyPanel.getPassword(), jTextFieldDirectory.getText(), jTextField_Name.getText(), overwrite);
            overwrite = false;
            actionKeyringListener.onConfirmAction(keyring);    
            dispose();
        } catch (KeyringException ex) {
            if(ex.getMessageType() != KeyringException.QUESTION_MESSAGE){
                JOptionPane.showMessageDialog(this, ex.getMessage(), ex.getTitle(), ex.getMessageType());
                return;
            }            
            int result = JOptionPane.showConfirmDialog(this, ex.getMessage(), ex.getTitle(), JOptionPane.YES_NO_CANCEL_OPTION);
            if(result != JOptionPane.YES_OPTION) return;
            
            overwrite = true;            
            jButtonConfirmActionPerformed(evt);
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbortActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonAbortActionPerformed

    private void jKeyPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jKeyPanelKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButtonConfirm.doClick();
        }
    }//GEN-LAST:event_jKeyPanelKeyPressed

    private void jButtonCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditsActionPerformed
        CreditsDialog c = new CreditsDialog((Frame) getParent(), true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
    }//GEN-LAST:event_jButtonCreditsActionPerformed

    private boolean overwrite = false;
    private final ActionDialogListener actionKeyringListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbort;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonCredits;
    private javax.swing.JButton jButtonSearchDirectory;
    private javax.swing.JFileChooser jFileChooser;
    private GUI.Components.JKeyPanel jKeyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JTextField jTextFieldDirectory;
    private javax.swing.JTextField jTextField_Name;
    // End of variables declaration//GEN-END:variables
}
