/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Exceptions.KeyringException;
import Classes.Folder;
import Classes.Directory;
import Classes.Page;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author AntoninoBonanno <https://github.com/AntoninoBonanno>
 */
public class UpsertFolderDialog extends javax.swing.JDialog {

    /**
     * Creates new form UpsertFolder
     * @param parent
     * @param modal
     * @param parentFolder Cartella padre all'oggetto dove si vuole aggiungere la cartella, NULL se <code>kObj</code> è <code>rootFolder</code>
     * @param kObj Oggetto dove si vuole aggiungere la cartella, NULL se si vuole modificare <code>parentFolder</code>
     * @throws Exceptions.KeyringException Se <code>parentFolder && kObj</code> sono NULL
     */
    public UpsertFolderDialog(java.awt.Frame parent, boolean modal, Folder parentFolder, Directory kObj) throws KeyringException {
        super(parent, modal);
        initComponents();
           
        if(parentFolder == null && kObj == null) throw new KeyringException("Errore.", "Errore", KeyringException.INFORMATION_MESSAGE);
        this.parentFolder = parentFolder;
        this.kObj = kObj;
        
        if(this.kObj == null){ 
            jTextField_name.setText(this.parentFolder.getName());
            setTitle("Modifica cartella");        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_confirm = new javax.swing.JButton();
        jButton_abort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi cartella");

        jTextField_name.setNextFocusableComponent(jButton_confirm);
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jLabel1.setText("Nome cartella:");

        jButton_confirm.setText("Conferma");
        jButton_confirm.setNextFocusableComponent(jButton_abort);
        jButton_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmActionPerformed(evt);
            }
        });

        jButton_abort.setText("Annulla");
        jButton_abort.setNextFocusableComponent(jTextField_name);
        jButton_abort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField_name)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 133, Short.MAX_VALUE)
                        .addComponent(jButton_confirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_abort)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_abort)
                    .addComponent(jButton_confirm))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmActionPerformed
        String name = jTextField_name.getText();
        try {
            if(kObj == null){
                parentFolder.edit(name);
                this.dispose();
                return;
            }
            
            if(kObj instanceof Page){
                Folder newFolder = parentFolder.convertPageToFolder((Page) kObj);
                newFolder.addSubfolder(name);
            } else {
                ((Folder) kObj).addSubfolder(name);
            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_confirmActionPerformed

    private void jButton_abortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abortActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_abortActionPerformed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton_confirm.doClick();
        }
    }//GEN-LAST:event_jTextField_nameKeyPressed

    
    private final Folder parentFolder;
    private final Directory kObj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_abort;
    private javax.swing.JButton jButton_confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
