/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Components;

import Utilities.PasswordUtils;
import java.awt.event.KeyListener;

/**
 *
 * @author AntoninoBonanno <https://github.com/AntoninoBonanno>
 */
public class JKeyPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPasswordPannel
     */
    public JKeyPanel() {
        this(true);
    }
    
    /**
     * Creates new form JPasswordPannel
     * 
     * @param showGenerate se si vuole mostrare il pulsante di generazione
     */
    public JKeyPanel(boolean showGenerate) {        
        initComponents();
        
        this.defaultEchoChar = jPasswordField.getEchoChar();
        jButtonGenerate.setVisible(showGenerate);
    }
    
    /**
     * Creates new form JPasswordPannel
     * @param nameField
     */
    public JKeyPanel(String nameField) {
        this();
        
        jLabelTitle.setText(nameField);  
        jPasswordField.setToolTipText(nameField+":");
        jLabelInsert.setText("Inserisci la " + nameField.toLowerCase());        
    }
    
    public String getPassword(){
        return String.valueOf(jPasswordField.getPassword());
    }
    
    public void setPassword(String password){
        jPasswordField.setText(password);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField = new javax.swing.JPasswordField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jButtonGenerate = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelInsert = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPasswordField.setToolTipText("Master Key");
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });

        jCheckBoxShowPass.setText("Mostra");
        jCheckBoxShowPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxShowPassStateChanged(evt);
            }
        });

        jButtonGenerate.setText("Genera");
        jButtonGenerate.setToolTipText("");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jLabelTitle.setText("Master Key:");

        jLabelInsert.setText("Inserisci la master key");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxShowPass))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerate))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsert)
                    .addComponent(jCheckBoxShowPass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxShowPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassStateChanged
        if (jCheckBoxShowPass.isSelected()) {
            jPasswordField.setEchoChar((char) 0);
        } else {
            jPasswordField.setEchoChar(defaultEchoChar);
        }    
    }//GEN-LAST:event_jCheckBoxShowPassStateChanged

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        jPasswordField.setText(PasswordUtils.generatePassword());
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        jPasswordField.requestFocus();
    }//GEN-LAST:event_formFocusGained

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        KeyListener[] keyListeners = getKeyListeners();
        for(KeyListener keyListener : keyListeners){
            keyListener.keyPressed(evt);
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private final char defaultEchoChar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabelInsert;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
