/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Components;

import Utilities.PasswordUtils;

/**
 *
 * @author Nino
 */
public class JKeyPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPasswordPannel
     */
    public JKeyPanel() {
        initComponents();
    }

    /**
     * Creates new form JPasswordPannel
     * @param nameField
     */
    public JKeyPanel(String nameField) {
        this();
        
        jLabel1.setText(nameField);
        jPasswordField.setToolTipText(nameField);
    }
    
    public String getPassword(){
        return String.valueOf(jPasswordField.getPassword());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField = new javax.swing.JPasswordField();
        jCheckBox_showPass = new javax.swing.JCheckBox();
        jButton_Generate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField.setToolTipText("Master Key");

        jCheckBox_showPass.setText("Mostra");
        jCheckBox_showPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_showPassStateChanged(evt);
            }
        });

        jButton_Generate.setText("Genera");
        jButton_Generate.setToolTipText("");
        jButton_Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenerateActionPerformed(evt);
            }
        });

        jLabel1.setText("Master Key:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Generate)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox_showPass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Generate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox_showPass))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_showPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_showPassStateChanged
        char defaultEchoChar = jPasswordField.getEchoChar();
        
        if (jCheckBox_showPass.isSelected()) {
            jPasswordField.setEchoChar((char) 0);
        } else {
            jPasswordField.setEchoChar(defaultEchoChar);
        }    
    }//GEN-LAST:event_jCheckBox_showPassStateChanged

    private void jButton_GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GenerateActionPerformed
        jPasswordField.setText(PasswordUtils.generatePassword());
    }//GEN-LAST:event_jButton_GenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Generate;
    private javax.swing.JCheckBox jCheckBox_showPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
